name: eslint
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
      - uses: borales/actions-yarn@v4
        with:
          cmd: lint
